services:
  postgres:
    container_name: despesas-postgres
    image: postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    environment:
      POSTGRES_USER: dbdespesas
      POSTGRES_PASSWORD: '#DBpass#@0250'
      POSTGRES_DB: alternativa-despesas
    expose:
      - 5432
    ports:
      - '127.0.0.1:5440:5432'
      - '[::1]:5440:5432'
